apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fangorn-tls
spec:
  secretName: fangorn-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - fangorn.cwnel.com
